### ISSUE TITLE
Missing functionallity from Milo\GitHub\Api

### ISSUE THREAD

**Issue by JanTvrdik** [bitbang/http#11]
The only functionality I currently miss in this library is one class which would provide API similar to Milo\GitHub\Api, most importantly `createRequest` (possibly without support for URI templates) and `decode`.

**Comment by milo** [comment]
I'm thinking about `Http\Client` class. But if so, the `Http\Clients\*` and `Http\IClient` should be renamed. Not sure how.

**Comment by milo** [comment]
Maybe `Executors\CurlExecutor` and `->execute()` for #2.

**Comment by JanTvrdik** [comment]
(Buzz call the top-level class `Browser`).

**Comment by milo** [comment]
Browser :+1:
