### ISSUE TITLE
Complete Readme so it's usable

### ISSUE THREAD

**Issue by TomasVotruba** [bitbang/http#14]
This package is suggested by https://github.com/kdyby/curl as replacement, but this package looks rather in dev/abandoned state itself.

Could you pls complete readme so it's easier to use? Thank you.

**Comment by janedbal** [comment]
@TomasVotruba :+1:

**Comment by milo** [comment]
This package is in v0.1, not abandoned. It's HTTP layer extracted from milo/github-api, some overview can be found in [here](https://github.com/milo/github-api/wiki/HTTP-clients) and [here](https://github.com/milo/github-api/wiki/Request-and-Response).

But it's mine own debt to write doc for it, I'll focus on it.

**Comment by TomasVotruba** [comment]
Thanks. These links are very helpful.

**Comment by milo** [comment]
Next small step https://github.com/bitbang/http/blob/master/doc/clients.md

**Comment by janedbal** [comment]
@milo The note in onRequest/onResponse events part should not be part of the formatted code :)

**Comment by TomasVotruba** [comment]
Not relevant anymore
