### ISSUE TITLE
Rename IClient::request()

### ISSUE THREAD

**Issue by milo** [bitbang/http#2]
Find better name.

**Comment by JanTvrdik** [comment]
How do you feel about `IClient::send()`?

**Comment by milo** [comment]
Sounds me asynchronously like `send()` & `receive()`. I'm thinking about `process()`.

**Comment by fprochazka** [comment]
curl is calling it exec... so maybe

``` php
$response = $client->execute($request);
```

?

**Comment by milo** [comment]
This naming problems sucks! And for the interface twice!

I have the word `execute` associated with something else, but the english vocabulary speaks for it. What about `perform()`?

**Comment by fprochazka** [comment]
Think twice before you create new naming convention. I'd suggest to you to look for examples elsewhere and choose one. Guzzle is pretty popular so maybe having similar name to that would be smart.

**Comment by milo** [comment]
@fprochazka I'm aware of it. That's why it's so hard :) The `execute()` will be fine I guess.

**Comment by JanTvrdik** [comment]
What about `sendSync()` and maybe `sendAsync` in the future (possibly in another repo depending on this one)?

**Comment by milo** [comment]
Request is a verb too. I'll not rename it.

**Comment by JanTvrdik** [comment]
Yes, request is a verb but it makes not sense "to request a request". You actually "request a response" by "sending a request" =)
