### ISSUE TITLE
CurlClient: unable to get really sent headers

### ISSUE THREAD

**Issue by janedbal** [bitbang/http#20]
Currently, I'm unable to log sent request headers correctly, because curl may send some HTTP headers not filled in Request::$headers. For example when you use [CURLOPT_ENCODING](http://cz.php.net/manual/en/function.curl-setopt.php#refsect1-function.curl-setopt-parameters). Below you can see some differences between my logger and headers received by [httpbin](https://httpbin.org/). Real sent headers may be obatained using [CURLINFO_HEADER_OUT](http://stackoverflow.com/a/8483805/1542616), but I'm not sure if modification of headers of Request object is a good way to go. What do you think?

```
GET http://httpbin.org/get HTTP/1.1
expect: 
connection: keep-alive
user-agent: Bitbang/0.1.0 (cURL)

HTTP/1.1 200
server: nginx
content-type: application/json
...

{
    "args": {},
    "headers": {
        "Accept": "*/*",
        "Accept-Encoding": "deflate, gzip",
        "Content-Length": "0",
        "Content-Type": "application/x-www-form-urlencoded",
        "Host": "httpbin.org",
        "User-Agent": "Bitbang/0.1.0 (cURL)"
    },
    "origin": "***",
    "url": "http://httpbin.org/get"
}

```

**Comment by milo** [comment]
Not sure how to deal with it. There can be other places, where headers are updated. E.g. some proxies, so request can be modified before comming to destination.

**Comment by janedbal** [comment]
You are right, this is problematic, headers may be added/modified on many levels (curl library, http server, proxy, ...) so this cannot be solved in php library itself.
